<fieldset class="fieldset create account">
    <legend class="legend"><span><?php echo __('Additional Information') ?></span></legend>
    <div class="field regulation required">
        <label for="regulation" class="label">
            <span><?php echo __('Office') ?></span>
        </label>
        <div class="field office required">
            <div class="control">
                <?php echo $block->getOfficesHtmlSelect(); ?>
            </div>
        </div>
    </div>
</fieldset>

